### ISSUE TITLE
Generation algorithm for k unique values in a given range

### ISSUE THREAD

**Issue by YeluriKetan** [YeluriKetan/project-GARAGE#1]
- Need to update the algorithm used for generating k unique values in a given closed range [a, b]
- Current algorithm is naïve and is placed as a temporary stub for the actual algorithm
- Access the function to update [here](https://github.com/YeluriKetan/project-GARAGE/blob/1020b94315d25c7da0630fc460fc8aa5e7fe4846/src/components/Data.js#L21)

**Comment by parzival979** [comment]
Algorithm Added and issue resolved in the Pull Request #4
